services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: 'redis-stack'
    ports:
      - '6379:6379'
    networks:
      - redis-network

  node-redis-consumer:
    build:
      context: ./RedisConsumer
      dockerfile: Dockerfile
    container_name: 'node-redis-consumer'
    ports:
      - '4000:4000'
    networks:
      - redis-network
    depends_on:
      - redis-stack
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: redis-stack
      REDIS_STREAMKEY: stream1
      REDIS_CONSUMER_GROUP: cg1
      REDIS_CONSUMER_NAME: consumer1
      REDIS_CONSUMER_PORT: 4000

  node-redis-producer:
    build:
      context: ./RedisProducer
      dockerfile: Dockerfile
    container_name: 'node-redis-producer'
    networks:
      - redis-network
    depends_on:
      - redis-stack
    ports:
      - '8081:8081'
    environment:
      PORT: 8081
      REDIS_PORT: 6379
      REDIS_HOST: redis-stack
      CORS_URLS: http://localhost:3000

networks:
  redis-network:
    name: redis-network

#  docker run --name nodejs-redis --net redis-network -p 8080:8080 -d redis/nodejs-redis
#  docker run --net redis-network  -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:latest
# docker run -d --net redis-network --name redisinsight -p 5540:5540 redis/redisinsight:latest